version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: estore-app
    container_name: app
    restart: unless-stopped
    volumes: 
      - ./:/var/www


  webserver:
    build: 
      context: .
      dockerfile: Nginx_Server_Dockerfile
    image: nginx
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./config/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app