version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: bfs-app-image
    container_name: bfs_man-app
    restart: unless-stopped
    volumes: 
      - ./:/var/www


  webserver:
    build: 
      context: .
      dockerfile: Nginx_Server_Dockerfile
    image: nginx
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./config/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app


  db:
    image: mysql:8.0.27
    container_name: mysql_db-server
    environment:
      MYSQL_DATABASE: file_data
      MYSQL_ROOT_PASSWORD: R00T@AdMiN
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql



volumes:
  dbdata:
    driver: local
